"""End-to-end tests for the `hdx` PyO3 binding over REGENERATED fixtures.

These tests prove the milestone's reviewable outcome (MS9-S3): the thin binding
mirrors the `hdx-core` verbs end-to-end from Python, and the §0 hard cut survives
all the way to a Python exception. They exercise the binding over the conformance
fixture trees — which are **git-ignored** and must be regenerated first by
``PYTHON=python3.12 conformance/generator/regenerate.sh`` (the runner
``crates/python/run_python_tests.sh`` does this before invoking pytest).

The three cases mirror the spec contract:

1. ``describe(valid)`` / ``validate(valid)`` return dicts whose top-level keys
   match the committed schemas, and ``validate(valid)["conformant"]`` is ``True``.
2. ``validate(invalid/missing-root-rollup)["conformant"]`` is ``False`` — a
   violated MUST that RAN surfaces unchanged as a normal report dict, NOT an
   exception (spec §14; the binding adds no contract logic).
3. ``describe`` / ``validate`` over ``invalid/wrong-format-version`` RAISE the
   dedicated hard-cut exception ``hdx.UnknownFormatVersionError`` — the spec §0
   hard version cut is preserved end-to-end and is NEVER softened into a
   ``conformant: false`` report.
"""

from __future__ import annotations

from pathlib import Path

import pytest

import hdx

# --- fixture paths (relative to the repo root; resolved from this file) ------
# This file lives at <repo>/crates/python/tests/test_mirror.py, so the repo root
# is three parents up. The fixture trees are git-ignored and regenerated by the
# runner before these tests run.
REPO_ROOT = Path(__file__).resolve().parents[3]
CONFORMANCE = REPO_ROOT / "conformance"

VALID_MINIMAL = CONFORMANCE / "valid" / "minimal"
VALID_GEOMETRY_LESS = CONFORMANCE / "valid" / "geometry-less"
INVALID_MISSING_ROOT_ROLLUP = CONFORMANCE / "invalid" / "missing-root-rollup"
INVALID_WRONG_FORMAT_VERSION = CONFORMANCE / "invalid" / "wrong-format-version"

# The schema-mandated top-level key sets (schemas/describe.schema.json,
# schemas/validate.schema.json). The binding reuses the verb's `*_json` string
# verbatim, so the parsed dict carries exactly these keys by construction (R4).
DESCRIBE_TOP_KEYS = {
    "manifest",
    "basins",
    "fields",
    "grids",
    "time_extents",
    "delineations",
}
VALIDATE_TOP_KEYS = {"checks", "conformant"}


def _require_fixture(path: Path) -> None:
    """Skip with a clear regenerate-first hint if a git-ignored fixture is absent."""
    if not path.exists():
        pytest.skip(
            f"fixture {path} is missing; run "
            "`PYTHON=python3.12 conformance/generator/regenerate.sh` first "
            "(fixtures are git-ignored). The runner crates/python/run_python_tests.sh "
            "does this automatically."
        )


def test_describe_valid_returns_schema_shaped_dict() -> None:
    """describe(valid) returns a dict whose top-level keys match the describe schema."""
    _require_fixture(VALID_MINIMAL)
    result = hdx.describe(str(VALID_MINIMAL))
    assert isinstance(result, dict)
    assert set(result.keys()) == DESCRIBE_TOP_KEYS


def test_validate_valid_is_conformant() -> None:
    """validate(valid) returns a schema-shaped dict with conformant True."""
    _require_fixture(VALID_MINIMAL)
    result = hdx.validate(str(VALID_MINIMAL))
    assert isinstance(result, dict)
    assert set(result.keys()) == VALIDATE_TOP_KEYS
    # `is True`: the verdict is a real bool, surfaced unchanged from hdx-core.
    assert result["conformant"] is True


def test_validate_geometry_less_is_conformant_under_0_2() -> None:
    """validate(valid/geometry-less) is conformant under 0.2 through the real PyO3 module.

    The geometry-optional 0.2 fixture (scalar_static present, outlines absent) surfaces
    conformant True — the binding transports the `validate_json` verdict verbatim. Geo1
    is skipped (no outlines); every other check ran:pass, so no fail flips the verdict.
    """
    _require_fixture(VALID_GEOMETRY_LESS)
    result = hdx.validate(str(VALID_GEOMETRY_LESS))
    assert isinstance(result, dict)
    assert set(result.keys()) == VALIDATE_TOP_KEYS
    assert result["conformant"] is True
    checks = {c["id"]: c for c in result["checks"]}
    assert len(checks) == 20, "all 20 §14 ids are reported"
    assert checks["L1"]["status"] == "ran" and checks["L1"]["result"] == "pass"
    assert checks["Geo1"]["status"] == "skipped", "Geo1 skips when outlines is absent (0.2)"


def test_describe_geometry_less_has_empty_delineations_under_0_2() -> None:
    """describe(valid/geometry-less) carries format_version 0.2 + empty delineations."""
    _require_fixture(VALID_GEOMETRY_LESS)
    result = hdx.describe(str(VALID_GEOMETRY_LESS))
    assert isinstance(result, dict)
    assert set(result.keys()) == DESCRIBE_TOP_KEYS
    assert result["manifest"]["format_version"] == "0.2"
    assert result["delineations"] == [], "a geometry-less dataset has empty delineations"


def test_validate_invalid_missing_root_rollup_is_not_conformant() -> None:
    """validate(invalid/missing-root-rollup) surfaces conformant False as a report.

    A violated MUST that RAN is a normal return (spec §14) — the binding does NOT
    raise here. This is the load-bearing distinction from the §0 hard cut below.
    """
    _require_fixture(INVALID_MISSING_ROOT_ROLLUP)
    result = hdx.validate(str(INVALID_MISSING_ROOT_ROLLUP))
    assert isinstance(result, dict)
    assert set(result.keys()) == VALIDATE_TOP_KEYS
    assert result["conformant"] is False


def test_validate_wrong_format_version_raises_hard_cut() -> None:
    """validate(wrong-format-version) RAISES the §0 hard-cut exception.

    The wrong `format_version` is the spec §0 hard cut: it must surface as
    `hdx.UnknownFormatVersionError`, NEVER as a softened `conformant: false`.
    """
    _require_fixture(INVALID_WRONG_FORMAT_VERSION)
    with pytest.raises(hdx.UnknownFormatVersionError):
        hdx.validate(str(INVALID_WRONG_FORMAT_VERSION))


def test_describe_wrong_format_version_raises_hard_cut() -> None:
    """describe(wrong-format-version) RAISES the §0 hard-cut exception too."""
    _require_fixture(INVALID_WRONG_FORMAT_VERSION)
    with pytest.raises(hdx.UnknownFormatVersionError):
        hdx.describe(str(INVALID_WRONG_FORMAT_VERSION))


def test_hard_cut_exception_is_an_hdx_error() -> None:
    """The hard-cut exception is a subclass of the HdxError base (catch-all works)."""
    assert issubclass(hdx.UnknownFormatVersionError, hdx.HdxError)
